development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: username
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  username: username
  password: password